/* Generated by scripts/build-pwa.mjs — do not edit. */
const CACHE_NAME = "circuit-pwa-92d59b81bd57a77d";
const PRECACHE_URLS = [
  "./",
  "./apple-touch-icon.png",
  "./assets/assets/sounds/long-beep.4e1d21981c088753f81f9c84e690e537.wav",
  "./assets/assets/sounds/short-beep.2b28efc336744fb7bee766fd63226e3b.wav",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/AntDesign.3f78af31cca60105799838a1a7a59fbd.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Entypo.31b5ffea3daddc69dd01a1f3d6cf63c5.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/EvilIcons.140c53a7643ea949007aa9a282153849.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Feather.ca4b48e04dc1ce10bfbddb262c8b835f.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome.b06871f281fee6b241d60582ae9369b9.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome5_Brands.3b89dd103490708d19a95adcae52210e.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome5_Regular.1f77739ca9ff2188b539c36f30ffa2be.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome5_Solid.605ed7926cf39a2ad5ec2d1f9d391d3d.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome6_Brands.56c8d80832e37783f12c05db7c8849e2.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome6_Regular.370dd5af19f8364907b6e2c41f45dbbf.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/FontAwesome6_Solid.adec7d6f310bc577f05e8fe06a5daccf.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Fontisto.b49ae8ab2dbccb02c4d11caaacf09eab.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Foundation.e20945d7c929279ef7a6f1db184a4470.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Ionicons.b4eb097d35f44ed943676fd56f6bdc51.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/MaterialCommunityIcons.6e435534bd35da5fef04168860a9b8fa.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/MaterialIcons.4e85bc9ebe07e0340c9c4fc2f6c38908.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Octicons.871378c6eab492a3e689a9385dc45a12.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/SimpleLineIcons.d2285965fe34b05465047401b8595dd0.ttf",
  "./assets/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Zocial.1681f34aaca71b8dfb70756bca331eb2.ttf",
  "./assets/node_modules/@expo-google-fonts/caprasimo/400Regular/Caprasimo_400Regular.54cc2fb9aeecccedde96c183678cbdd8.ttf",
  "./assets/node_modules/@expo-google-fonts/figtree/300Light/Figtree_300Light.4d0b973d5fe9d48fafbc101aeb6addcc.ttf",
  "./assets/node_modules/@expo-google-fonts/figtree/300Light_Italic/Figtree_300Light_Italic.924864a4ae5cd26c081f68749aa5f78d.ttf",
  "./assets/node_modules/@expo-google-fonts/figtree/400Regular/Figtree_400Regular.fde4a0ff6b61f88efd09f91f41c9a6da.ttf",
  "./assets/node_modules/@expo-google-fonts/figtree/400Regular_Italic/Figtree_400Regular_Italic.9d65a509684b10766dfc3238d886a494.ttf",
  "./assets/node_modules/@expo-google-fonts/figtree/500Medium/Figtree_500Medium.0493473149844cee7b601ff24ef1479d.ttf",
  "./assets/node_modules/@expo-google-fonts/figtree/500Medium_Italic/Figtree_500Medium_Italic.959f16743828a114ddbcdcfddfd62570.ttf",
  "./assets/node_modules/@expo-google-fonts/figtree/600SemiBold/Figtree_600SemiBold.0aea8911a39371620ecd59ab2a49e642.ttf",
  "./assets/node_modules/@expo-google-fonts/figtree/600SemiBold_Italic/Figtree_600SemiBold_Italic.c42d5ab1b2f5144bc6157c508a9bccb0.ttf",
  "./assets/node_modules/@expo-google-fonts/figtree/700Bold/Figtree_700Bold.c35c3ee5c1bab1acfe1e0d71549dd501.ttf",
  "./assets/node_modules/@expo-google-fonts/figtree/700Bold_Italic/Figtree_700Bold_Italic.219abf857325ba545376cb9cc2e08508.ttf",
  "./assets/node_modules/@expo-google-fonts/figtree/800ExtraBold/Figtree_800ExtraBold.2960d6e099892183db5484444ed152c0.ttf",
  "./assets/node_modules/@expo-google-fonts/figtree/800ExtraBold_Italic/Figtree_800ExtraBold_Italic.dd801cdb59f2b2542036026cfa68600e.ttf",
  "./assets/node_modules/@expo-google-fonts/figtree/900Black/Figtree_900Black.cb929048af7ca7945e057d80cd579809.ttf",
  "./assets/node_modules/@expo-google-fonts/figtree/900Black_Italic/Figtree_900Black_Italic.c6dcb279022586ad20660a894013a492.ttf",
  "./assets/node_modules/@react-navigation/elements/lib/module/assets/back-icon-mask.0a328cd9c1afd0afe8e3b1ec5165b1b4.png",
  "./assets/node_modules/@react-navigation/elements/lib/module/assets/back-icon.35ba0eaec5a4f5ed12ca16fabeae451d.png",
  "./assets/node_modules/@react-navigation/elements/lib/module/assets/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55.png",
  "./assets/node_modules/@react-navigation/elements/lib/module/assets/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55@2x.png",
  "./assets/node_modules/@react-navigation/elements/lib/module/assets/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55@3x.png",
  "./assets/node_modules/@react-navigation/elements/lib/module/assets/clear-icon.c94f6478e7ae0cdd9f15de1fcb9e5e55@4x.png",
  "./assets/node_modules/@react-navigation/elements/lib/module/assets/close-icon.808e1b1b9b53114ec2838071a7e6daa7.png",
  "./assets/node_modules/@react-navigation/elements/lib/module/assets/close-icon.808e1b1b9b53114ec2838071a7e6daa7@2x.png",
  "./assets/node_modules/@react-navigation/elements/lib/module/assets/close-icon.808e1b1b9b53114ec2838071a7e6daa7@3x.png",
  "./assets/node_modules/@react-navigation/elements/lib/module/assets/close-icon.808e1b1b9b53114ec2838071a7e6daa7@4x.png",
  "./assets/node_modules/@react-navigation/elements/lib/module/assets/search-icon.286d67d3f74808a60a78d3ebf1a5fb57.png",
  "./icon-192.png",
  "./icon-512.png",
  "./index.html",
  "./manifest.webmanifest",
  "./static/static/css/web-1dc77de962383f53fd06d835fc760008.css",
  "./static/static/js/web/AppEntry-c53ba3c5f4e50bc0fdfbf588235a24e3.js"
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches
      .open(CACHE_NAME)
      // "no-cache" bypasses the browser HTTP cache so a stale index.html can
      // never be precached alongside a newer service worker.
      .then((cache) => cache.addAll(PRECACHE_URLS.map((url) => new Request(url, { cache: "no-cache" }))))
      .then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys.filter((key) => key.startsWith("circuit-pwa-") && key !== CACHE_NAME).map((key) => caches.delete(key)),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") {
    return;
  }

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) {
    return;
  }

  // SPA: serve the cached shell for navigations, cache-first for assets.
  const isNavigation = request.mode === "navigate";
  event.respondWith(
    caches.open(CACHE_NAME).then(async (cache) => {
      const cached = await cache.match(isNavigation ? "./" : request);
      if (cached) {
        return cached;
      }

      const response = await fetch(request);
      if (response.ok) {
        cache.put(request, response.clone());
      }
      return response;
    }),
  );
});
